fetch existing dns records
containeroo/cloudflare-operator pull request #140
Opened 2022-08-16 08:56 UTC by gi8lino

2022-08-16 13:33 UTC, rxbn requested changes

2022-08-16 13:33 UTC, rxbn commented on docs/content/getting_started.md
> +    Because cloudflare-operator should be the single source of truth, __ALL__ existing `A`, `AAAA` and `CNAME` DNS Records in the given Cloudflare Zone will be __ DELETED__ if there is no correspondi
```suggestion
    Because cloudflare-operator should be the single source of truth, __ALL__ existing `A`, `AAAA` and `CNAME` DNS records in the given Cloudflare zone will be __ DELETED__ if there is no corresponding `DNSRecord` object in Kubernetes.
```

2022-08-16 13:33 UTC, rxbn commented on docs/content/installation.md
> +    Because cloudflare-operator should be the single source of truth, __ALL__ existing `A`, `AAAA` and `CNAME` DNS Records in the given Cloudflare Zone will be __ DELETED__ if there is no correspondi
```suggestion
    Because cloudflare-operator should be the single source of truth, __ALL__ existing `A`, `AAAA` and `CNAME` DNS records in the given Cloudflare zone will be __ DELETED__ if there is no corresponding `DNSRecord` object in Kubernetes.
```

2022-08-16 13:33 UTC, rxbn commented on docs/content/installation.md
> +See [operations](operations.md#existing-cloudflare-dns-records)
```suggestion
There is a script available to convert preexisting Cloudflare DNS records to Kubernetes `DNSRecord` objects. Learn more [here](operations.md#existing-cloudflare-dns-records).
```

2022-08-16 13:33 UTC, rxbn commented on docs/content/operations.md
> +In `hack/fetch_dns_records.sh` is a helper script to fetch all Cloudflare DNS Records for a given Cloudflare Zone (`CLOUDFLARE_ZONE_ID`) and outputs cloudflare-operator `DNSRecords` objects.
```suggestion
In `hack/fetch_dns_records.sh` is a helper script to fetch all Cloudflare DNS records for a given Cloudflare zone (`CLOUDFLARE_ZONE_ID`) and outputs cloudflare-operator `DNSRecord` objects.
```

2022-08-16 13:33 UTC, rxbn commented on docs/content/operations.md
> +set mandatory variables:
```suggestion
Set environment variables:
```

2022-08-16 13:33 UTC, rxbn commented on docs/content/operations.md
> +run script and write output to a file:
```suggestion
Run script and write output to a file:
```

2022-08-16 13:33 UTC, rxbn commented on docs/content/operations.md
> +check if everything is looking good:
```suggestion
Verify script output:
```

2022-08-16 13:33 UTC, rxbn commented on docs/content/operations.md
> +create `DNSRecords`:
```suggestion
Create `DNSRecords`:
```

2022-10-07 16:56 UTC, gi8lino commented
separate pr is comming

2022-10-07 16:56 UTC, closed without merging